# Generated by Django 2.0.6 on 2018-07-26 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180726_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='userId',
        ),
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.ManyToManyField(to='users.Badge'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(to='users.Skill'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='createdOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='createdOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(),
        ),
    ]
